package Text::Xslate::Compiler::PPBooster;

use Any::Moose;
use Any::Moose '::Util::TypeConstraints';
use Text::Xslate::Util qw(
    value_to_literal
);


extends qw(Text::Xslate::Compiler);

use Text::Xslate::Compiler::PPBooster::CodeGenerator;

sub as_assembly { # it makes a pp::booster code.
    my($self, $asm ) = @_;
    my $perlcode = sprintf( "ppbooster\n%s",
        Text::Xslate::Compiler::PPBooster::CodeGenerator->new()->opcode_to_perlcode_string( $asm )
    );
    $self->SUPER::as_assembly( $asm )
    . "# below liens are generated by Compiler::PPBooster.\n"
    . $perlcode;
}

no Any::Moose;
no Any::Moose '::Util::TypeConstraints';

__PACKAGE__->meta->make_immutable;

__END__

=head1 NAME

Text::Xslate::Compiler::PPBooster - The Xslate compiler for PP::Booster

=head1 DESCRIPTION

This is the Xslate compiler to generate the intermediate code from the
abstract syntax tree that parsers build from templates.

=head1 SEE ALSO

L<Text::Xslate>

L<Text::Xslate::Parser>

L<Text::Xslate::PP::Booster>

=cut
